# Generated by Django 2.0.7 on 2018-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeunravelservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
